### ISSUE TITLE
Configuration should be passed in as env variables

### ISSUE THREAD

**Issue by lumberj** [interledger/five-bells-notary#10]
To make this consistent with other Five-Bells projects. For example, `NOTARY_PORT` should be an environment variable that changes the default listen port.

**Comment by justmoon** [comment]
It is. See: https://github.com/interledger/five-bells-notary/blob/master/src/lib/config.js

Notary uses five-bells-shared which takes care of parsing env variables like `NOTARY_PORT`. Try it, it works.

Just needs to be documented in the README.
